# SPDX-License-Identifier: MPL-2.0

[brick]
name = "mass-panic"
version = "0.1.0"
chplVersion = "2.8.0"
authors = ["Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>"]
license = "MPL-2.0"

[dependencies]
