# SPDX-License-Identifier: PMPL-1.0-or-later
# panic-attack shell completions for zsh
# Generated by: panic-attack completions zsh
# Author: Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>

#compdef panic-attack

autoload -U is-at-least

_panic-attack() {
    typeset -A opt_args
    typeset -a _arguments_options
    local ret=1

    if is-at-least 5.2; then
        _arguments_options=(-s -S -C)
    else
        _arguments_options=(-s -C)
    fi

    local context curcontext="$curcontext" state line
    _arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
'-V[Print version]' \
'--version[Print version]' \
":: :_panic-attack_commands" \
"*::: :->panic-attack" \
&& ret=0
    case $state in
    (panic-attack)
        words=($line[1] "${words[@]}")
        (( CURRENT += 1 ))
        curcontext="${curcontext%:*:*}:panic-attack-command-$line[1]:"
        case $line[1] in
            (assail)
_arguments "${_arguments_options[@]}" : \
'-o+[Output report to file]:OUTPUT:_files' \
'--output=[Output report to file]:OUTPUT:_files' \
'--signing-key=[Path to Ed25519 private key (32-byte seed) for signing the attestation. Requires the \`signing\` feature]:PATH:_files' \
'--logtalk=[Export kanren logic facts as Logtalk predicates for hypatia integration]:PATH:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'-v[Verbose output]' \
'--verbose[Verbose output]' \
'--attest[Enable attestation chain (writes .attestation.json sidecar)]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':target -- Target program or directory to analyze:_files' \
&& ret=0
;;
(attack)
_arguments "${_arguments_options[@]}" : \
'--profile=[Attack profile file (json/yaml)]:PROFILE:_files' \
'*--arg=[Extra argument(s) passed to the target program]:ARG:_default' \
'*--axis-arg=[Axis-specific argument, format\: AXIS=ARG]:AXIS=ARG:_default' \
'--probe=[Probe mode for detecting unsupported flags]:PROBE:(auto always never)' \
'-a+[Attack axis to use]:AXIS:(cpu memory disk network concurrency time)' \
'--axis=[Attack axis to use]:AXIS:(cpu memory disk network concurrency time)' \
'-i+[Attack intensity]:INTENSITY:(light medium heavy extreme)' \
'--intensity=[Attack intensity]:INTENSITY:(light medium heavy extreme)' \
'-d+[Attack duration in seconds]:DURATION:_default' \
'--duration=[Attack duration in seconds]:DURATION:_default' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':program -- Target program to attack:_files' \
&& ret=0
;;
(assault)
_arguments "${_arguments_options[@]}" : \
'--source=[Source directory or file for assail analysis (defaults to PROGRAM)]:PATH:_files' \
'--profile=[Attack profile file (json/yaml)]:PROFILE:_files' \
'*--arg=[Extra argument(s) passed to the target program]:ARG:_default' \
'*--axis-arg=[Axis-specific argument, format\: AXIS=ARG]:AXIS=ARG:_default' \
'--probe=[Probe mode for detecting unsupported flags]:PROBE:(auto always never)' \
'*-a+[Attack axes (default\: all)]:AXES:(cpu memory disk network concurrency time)' \
'*--axes=[Attack axes (default\: all)]:AXES:(cpu memory disk network concurrency time)' \
'-i+[Attack intensity]:INTENSITY:(light medium heavy extreme)' \
'--intensity=[Attack intensity]:INTENSITY:(light medium heavy extreme)' \
'-d+[Attack duration per axis in seconds]:DURATION:_default' \
'--duration=[Attack duration per axis in seconds]:DURATION:_default' \
'-o+[Output report to file]:OUTPUT:_files' \
'--output=[Output report to file]:OUTPUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':program -- Target program to assault:_files' \
&& ret=0
;;
(ambush)
_arguments "${_arguments_options[@]}" : \
'--source=[Source directory or file for assail analysis (defaults to PROGRAM)]:PATH:_files' \
'--timeline=[Timeline file (JSON/YAML) for DAW-style scheduling]:TIMELINE:_files' \
'--profile=[Attack profile file (json/yaml) for target args]:PROFILE:_files' \
'*--arg=[Extra argument(s) passed to the target program]:ARG:_default' \
'*--axis-arg=[Axis-specific argument, format\: AXIS=ARG]:AXIS=ARG:_default' \
'*-a+[Stress axes to apply (default\: all)]:AXES:(cpu memory disk network concurrency time)' \
'*--axes=[Stress axes to apply (default\: all)]:AXES:(cpu memory disk network concurrency time)' \
'-i+[Stress intensity]:INTENSITY:(light medium heavy extreme)' \
'--intensity=[Stress intensity]:INTENSITY:(light medium heavy extreme)' \
'-d+[Ambush duration per axis in seconds]:DURATION:_default' \
'--duration=[Ambush duration per axis in seconds]:DURATION:_default' \
'-o+[Output report to file]:OUTPUT:_files' \
'--output=[Output report to file]:OUTPUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':program -- Target program to ambush:_files' \
&& ret=0
;;
(amuck)
_arguments "${_arguments_options[@]}" : \
'--preset=[Mutation preset when no --spec is provided]:PRESET:(light dangerous)' \
'--spec=[Custom mutation combinations file (json/yaml)]:SPEC:_files' \
'--max-combinations=[Maximum combinations to execute]:MAX_COMBINATIONS:_default' \
'--output-dir=[Directory where mutated variants are written]:DIR:_files' \
'--exec-program=[Optional executable run per mutated file]:PROGRAM:_default' \
'*--exec-arg=[Arguments for --exec-program; use {file} for the mutated file path]:ARG:_default' \
'-o+[Optional report output path (JSON)]:OUT:_files' \
'--output=[Optional report output path (JSON)]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':target -- Target file to mutate (never modified in place):_files' \
&& ret=0
;;
(abduct)
_arguments "${_arguments_options[@]}" : \
'--source-root=[Optional source root used to resolve dependency graph paths]:PATH:_files' \
'--scope=[Dependency scope for selecting related files]:SCOPE:(none direct two-hops directory)' \
'--output-dir=[Workspace root where abduct runs are created]:DIR:_files' \
'--mtime-offset-days=[Shift copied file mtimes by this many days (negative or positive)]:MTIME_OFFSET_DAYS:_default' \
'--time-mode=[Time mode metadata exported to executed process]:TIME_MODE:(normal frozen slow)' \
'--time-scale=[Virtual time scale factor when --time-mode slow]:TIME_SCALE:_default' \
'--virtual-now=[Optional virtual timestamp (RFC3339) exported as ABDUCT_VIRTUAL_NOW]:TIMESTAMP:_default' \
'--exec-program=[Optional executable to run after lock/time setup]:PROGRAM:_default' \
'*--exec-arg=[Arguments for --exec-program; placeholders\: {file}, {workspace}]:ARG:_default' \
'--exec-timeout=[Timeout (seconds) for the optional execution command]:EXEC_TIMEOUT:_default' \
'-o+[Optional report output path (JSON)]:OUT:_files' \
'--output=[Optional report output path (JSON)]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--no-lock[Disable readonly lock-down of copied files]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':target -- Target file to abduct into an isolated workspace:_files' \
&& ret=0
;;
(adjudicate)
_arguments "${_arguments_options[@]}" : \
'-o+[Optional report output path (JSON)]:OUT:_files' \
'--output=[Optional report output path (JSON)]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
'*::reports -- Input report files (assault/amuck/abduct JSON, assault YAML):_files' \
&& ret=0
;;
(axial)
_arguments "${_arguments_options[@]}" : \
'--exec-program=[Optional executable to run for reaction observation]:PROGRAM:_default' \
'*--exec-arg=[Arguments for --exec-program; placeholder\: {target}]:ARG:_default' \
'--repeat=[Number of repeated observation runs for --exec-program]:REPEAT:_default' \
'--timeout=[Timeout (seconds) per observation run]:TIMEOUT:_default' \
'*--report=[Existing reports to observe (can be provided multiple times)]:PATH:_files' \
'--head=[Include the first N lines from observed output/content]:HEAD:_default' \
'--tail=[Include the last N lines from observed output/content]:TAIL:_default' \
'*--grep=[Exact pattern search (repeatable)]:PATTERN:_default' \
'*--agrep=[Approximate/fuzzy pattern search (repeatable)]:PATTERN:_default' \
'--agrep-distance=[Maximum edit distance for --agrep matches]:AGREP_DISTANCE:_default' \
'--lang=[Output language (ISO 639-1 code\: en, es, fr, de, ja)]:LANG:(en es fr de ja)' \
'--aspell-lang=[Aspell dictionary language (default derived from --lang)]:CODE:_default' \
'--markdown-output=[Optional markdown output path]:OUT:_files' \
'--pandoc-to=[Optional pandoc target format (e.g. html, docx, gfm, latex)]:FMT:_default' \
'--pandoc-output=[Optional pandoc output path (required for custom destination)]:OUT:_files' \
'-o+[Optional report output path (JSON)]:OUT:_files' \
'--output=[Optional report output path (JSON)]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--aspell[Enable aspell checks on observed text]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':target -- Target file/program under observation:_files' \
&& ret=0
;;
(analyze)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':report -- Crash report file (JSON):_files' \
&& ret=0
;;
(report)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':report -- JSON assault report path:_files' \
&& ret=0
;;
(tui)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':report -- Assault report JSON file:_files' \
&& ret=0
;;
(gui)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':report -- Assault report JSON file:_files' \
&& ret=0
;;
(diff)
_arguments "${_arguments_options[@]}" : \
'--verisimdb-dir=[VerisimDB directory to scan for latest reports]:DIR:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
'::base -- Base report path:_files' \
'::compare -- Compare report path:_files' \
&& ret=0
;;
(manifest)
_arguments "${_arguments_options[@]}" : \
'-p+[Alternate AI manifest file]:PATH:_files' \
'--path=[Alternate AI manifest file]:PATH:_files' \
'-o+[Save Nickel output to file]:OUT:_files' \
'--output=[Save Nickel output to file]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
&& ret=0
;;
(a2ml-export)
_arguments "${_arguments_options[@]}" : \
'--kind=[Report kind to encode in the bundle]:KIND:(assail attack assault ambush amuck abduct adjudicate axial)' \
'-o+[Destination A2ML file]:OUT:_files' \
'--output=[Destination A2ML file]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':input -- Source report file (json/yaml depending on kind):_files' \
&& ret=0
;;
(a2ml-import)
_arguments "${_arguments_options[@]}" : \
'-o+[Destination JSON file]:OUT:_files' \
'--output=[Destination JSON file]:OUT:_files' \
'--kind=[Optional expected kind check]:KIND:(assail attack assault ambush amuck abduct adjudicate axial)' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':input -- Source A2ML bundle file:_files' \
&& ret=0
;;
(panll)
_arguments "${_arguments_options[@]}" : \
'-o+[Output file for PanLL export (JSON)]:OUT:_files' \
'--output=[Output file for PanLL export (JSON)]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':report -- Assault report JSON/YAML file:_files' \
&& ret=0
;;
(help)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
'::command -- Optional subcommand name to display help for:_default' \
&& ret=0
;;
(assemblyline)
_arguments "${_arguments_options[@]}" : \
'-o+[Output report to file]:OUTPUT:_files' \
'--output=[Output report to file]:OUTPUT:_files' \
'--min-findings=[Minimum number of findings to include a repo]:MIN_FINDINGS:_default' \
'--cache=[Path to fingerprint cache file (default\: .panic-attack-cache.json in DIRECTORY)]:FILE:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--findings-only[Only show repos with findings]' \
'--incremental[Enable incremental scanning (skip repos unchanged since last run)]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':directory -- Parent directory containing repos to scan:_files' \
&& ret=0
;;
(diagnostics)
_arguments "${_arguments_options[@]}" : \
'--manifest=[Alternate AI manifest file (default\: AI.a2ml)]:PATH:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
&& ret=0
;;
(migration-snapshot)
_arguments "${_arguments_options[@]}" : \
'--label=[Label for this snapshot (e.g. "before", "after", "v12-trial")]:LABEL:_default' \
'-o+[Output snapshot to file]:OUTPUT:_files' \
'--output=[Output snapshot to file]:OUTPUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--build-time[Measure build time (runs \`rescript build\`)]' \
'--bundle-size[Measure bundle size (scans output directory)]' \
'--store[Store snapshot as VeriSimDB hexad]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':target -- Target ReScript project directory:_files' \
&& ret=0
;;
(migration-diff)
_arguments "${_arguments_options[@]}" : \
'-o+[Output diff report to file]:OUTPUT:_files' \
'--output=[Output diff report to file]:OUTPUT:_files' \
'--format=[Output format (markdown or json)]:FORMAT:(markdown json)' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':before -- Before snapshot JSON file:_files' \
':after -- After snapshot JSON file:_files' \
&& ret=0
;;
(notify)
_arguments "${_arguments_options[@]}" : \
'-o+[Output markdown file]:OUT:_files' \
'--output=[Output markdown file]:OUT:_files' \
'--min-findings=[Minimum findings to include a repo]:MIN_FINDINGS:_default' \
'--github-owner=[GitHub owner for issue creation]:GITHUB_OWNER:_default' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--critical-only[Only include repos with critical findings]' \
'--create-issues[Create GitHub issues for repos with critical findings (requires gh CLI)]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':report -- Assemblyline JSON report file:_files' \
&& ret=0
;;
(image)
_arguments "${_arguments_options[@]}" : \
'-o+[Output file for the system image JSON]:OUT:_files' \
'--output=[Output file for the system image JSON]:OUT:_files' \
'--cache=[Fingerprint cache file]:FILE:_files' \
'--label=[Label for the temporal snapshot]:LABEL:_default' \
'--verisimdb-dir=[VeriSimDB directory for snapshots]:DIR:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--incremental[Enable incremental scanning]' \
'--snapshot[Take a temporal snapshot (writes to VeriSimDB)]' \
'--panll[Export PanLL-format system image alongside raw output]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':directory -- Parent directory containing repos to scan (runs assemblyline internally):_files' \
&& ret=0
;;
(temporal)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
":: :_panic-attack__temporal_commands" \
"*::: :->temporal" \
&& ret=0

    case $state in
    (temporal)
        words=($line[1] "${words[@]}")
        (( CURRENT += 1 ))
        curcontext="${curcontext%:*:*}:panic-attack-temporal-command-$line[1]:"
        case $line[1] in
            (list)
_arguments "${_arguments_options[@]}" : \
'--verisimdb-dir=[VeriSimDB directory]:DIR:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
&& ret=0
;;
(diff)
_arguments "${_arguments_options[@]}" : \
'--verisimdb-dir=[VeriSimDB directory]:DIR:_files' \
'-o+[Output diff report to file]:OUT:_files' \
'--output=[Output diff report to file]:OUT:_files' \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--panll[Export PanLL-format temporal diff alongside raw output]' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':from_seq -- Sequence number of the older snapshot:_default' \
':to_seq -- Sequence number of the newer snapshot:_default' \
&& ret=0
;;
        esac
    ;;
esac
;;
(completions)
_arguments "${_arguments_options[@]}" : \
'--report-view=[]:REPORT_VIEW:(summary accordion dashboard matrix)' \
'--output-format=[]:OUTPUT_FORMAT:(json yaml nickel sarif)' \
'--store=[]:DIR:_files' \
'--expand-sections[]' \
'--pivot[]' \
'--quiet[]' \
'--parallel[]' \
'-h[Print help]' \
'--help[Print help]' \
':shell -- Shell to generate completions for:(bash zsh fish nushell powershell)' \
&& ret=0
;;
        esac
    ;;
esac
}

(( $+functions[_panic-attack_commands] )) ||
_panic-attack_commands() {
    local commands; commands=(
'assail:Run assail static analysis on a target program' \
'attack:Execute a single attack on a target program' \
'assault:Full assault\: combines static analysis (\`assail\`) with multi-axis dynamic attacks (\`attack\`)' \
'ambush:Ambush\: run a target program while applying ambient stressors' \
'amuck:Amuck\: mutate a file with dangerous/user-defined combinations and optionally execute checks' \
'abduct:Abduct\: isolate, lock, and time-skew a target file (optionally with dependencies)' \
'adjudicate:Adjudicate\: aggregate reports into a campaign-wide expert-system verdict' \
'axial:Axial\: observe target reactions across attack axes from tool outputs and report artifacts' \
'analyze:Analyze crash reports for bug signatures' \
'report:Render a saved assault report with view controls' \
'tui:Interactive review of a saved report' \
'gui:GUI review of a saved report' \
'diff:Compare two assault reports (defaults to latest VerisimDB runs)' \
'manifest:Export the AI manifest as Nickel' \
'a2ml-export:Export a report file into the A2ML report-bundle document type' \
'a2ml-import:Import an A2ML report-bundle file back into JSON' \
'panll:Export an assault report as a PanLL event-chain model' \
'help:Print detailed help text (man-style)' \
'assemblyline:Assemblyline\: batch-scan a directory of repos (assail each, aggregate results)' \
'diagnostics:Run panic-attack self-diagnostics for Hypatia/gitbot-fleet visibility' \
'migration-snapshot:Take a ReScript migration snapshot (assail + migration metrics)' \
'migration-diff:Compare two migration snapshots and produce a diff report' \
'notify:Notify\: generate annotated findings summary from an assemblyline report' \
'image:Image\: generate a system health image from an assemblyline scan (fNIRS-style)' \
'temporal:Temporal\: navigate system health through time (diff, list, replay)' \
'completions:Generate shell completions for the specified shell' \
    )
    _describe -t commands 'panic-attack commands' commands "$@"
}
(( $+functions[_panic-attack__a2ml-export_commands] )) ||
_panic-attack__a2ml-export_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack a2ml-export commands' commands "$@"
}
(( $+functions[_panic-attack__a2ml-import_commands] )) ||
_panic-attack__a2ml-import_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack a2ml-import commands' commands "$@"
}
(( $+functions[_panic-attack__abduct_commands] )) ||
_panic-attack__abduct_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack abduct commands' commands "$@"
}
(( $+functions[_panic-attack__adjudicate_commands] )) ||
_panic-attack__adjudicate_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack adjudicate commands' commands "$@"
}
(( $+functions[_panic-attack__ambush_commands] )) ||
_panic-attack__ambush_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack ambush commands' commands "$@"
}
(( $+functions[_panic-attack__amuck_commands] )) ||
_panic-attack__amuck_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack amuck commands' commands "$@"
}
(( $+functions[_panic-attack__analyze_commands] )) ||
_panic-attack__analyze_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack analyze commands' commands "$@"
}
(( $+functions[_panic-attack__assail_commands] )) ||
_panic-attack__assail_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack assail commands' commands "$@"
}
(( $+functions[_panic-attack__assault_commands] )) ||
_panic-attack__assault_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack assault commands' commands "$@"
}
(( $+functions[_panic-attack__assemblyline_commands] )) ||
_panic-attack__assemblyline_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack assemblyline commands' commands "$@"
}
(( $+functions[_panic-attack__attack_commands] )) ||
_panic-attack__attack_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack attack commands' commands "$@"
}
(( $+functions[_panic-attack__axial_commands] )) ||
_panic-attack__axial_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack axial commands' commands "$@"
}
(( $+functions[_panic-attack__completions_commands] )) ||
_panic-attack__completions_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack completions commands' commands "$@"
}
(( $+functions[_panic-attack__diagnostics_commands] )) ||
_panic-attack__diagnostics_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack diagnostics commands' commands "$@"
}
(( $+functions[_panic-attack__diff_commands] )) ||
_panic-attack__diff_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack diff commands' commands "$@"
}
(( $+functions[_panic-attack__gui_commands] )) ||
_panic-attack__gui_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack gui commands' commands "$@"
}
(( $+functions[_panic-attack__help_commands] )) ||
_panic-attack__help_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack help commands' commands "$@"
}
(( $+functions[_panic-attack__image_commands] )) ||
_panic-attack__image_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack image commands' commands "$@"
}
(( $+functions[_panic-attack__manifest_commands] )) ||
_panic-attack__manifest_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack manifest commands' commands "$@"
}
(( $+functions[_panic-attack__migration-diff_commands] )) ||
_panic-attack__migration-diff_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack migration-diff commands' commands "$@"
}
(( $+functions[_panic-attack__migration-snapshot_commands] )) ||
_panic-attack__migration-snapshot_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack migration-snapshot commands' commands "$@"
}
(( $+functions[_panic-attack__notify_commands] )) ||
_panic-attack__notify_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack notify commands' commands "$@"
}
(( $+functions[_panic-attack__panll_commands] )) ||
_panic-attack__panll_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack panll commands' commands "$@"
}
(( $+functions[_panic-attack__report_commands] )) ||
_panic-attack__report_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack report commands' commands "$@"
}
(( $+functions[_panic-attack__temporal_commands] )) ||
_panic-attack__temporal_commands() {
    local commands; commands=(
'list:List all temporal snapshots' \
'diff:Diff two temporal snapshots' \
    )
    _describe -t commands 'panic-attack temporal commands' commands "$@"
}
(( $+functions[_panic-attack__temporal__diff_commands] )) ||
_panic-attack__temporal__diff_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack temporal diff commands' commands "$@"
}
(( $+functions[_panic-attack__temporal__list_commands] )) ||
_panic-attack__temporal__list_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack temporal list commands' commands "$@"
}
(( $+functions[_panic-attack__tui_commands] )) ||
_panic-attack__tui_commands() {
    local commands; commands=()
    _describe -t commands 'panic-attack tui commands' commands "$@"
}

if [ "$funcstack[1]" = "_panic-attack" ]; then
    _panic-attack "$@"
else
    compdef _panic-attack panic-attack
fi
