# SPDX-License-Identifier: PMPL-1.0-or-later
# panic-attack shell completions for fish
# Generated by: panic-attack completions fish
# Author: Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>

# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_panic_attack_global_optspecs
	string join \n report-view= expand-sections output-format= pivot store= quiet parallel h/help V/version
end

function __fish_panic_attack_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_panic_attack_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_panic_attack_using_subcommand
	set -l cmd (__fish_panic_attack_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c panic-attack -n "__fish_panic_attack_needs_command" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_needs_command" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_needs_command" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_needs_command" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_needs_command" -l pivot
complete -c panic-attack -n "__fish_panic_attack_needs_command" -l quiet
complete -c panic-attack -n "__fish_panic_attack_needs_command" -l parallel
complete -c panic-attack -n "__fish_panic_attack_needs_command" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -s V -l version -d 'Print version'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "assail" -d 'Run assail static analysis on a target program'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "attack" -d 'Execute a single attack on a target program'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "assault" -d 'Full assault: combines static analysis (`assail`) with multi-axis dynamic attacks (`attack`)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "ambush" -d 'Ambush: run a target program while applying ambient stressors'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "amuck" -d 'Amuck: mutate a file with dangerous/user-defined combinations and optionally execute checks'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "abduct" -d 'Abduct: isolate, lock, and time-skew a target file (optionally with dependencies)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "adjudicate" -d 'Adjudicate: aggregate reports into a campaign-wide expert-system verdict'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "axial" -d 'Axial: observe target reactions across attack axes from tool outputs and report artifacts'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "analyze" -d 'Analyze crash reports for bug signatures'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "report" -d 'Render a saved assault report with view controls'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "tui" -d 'Interactive review of a saved report'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "gui" -d 'GUI review of a saved report'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "diff" -d 'Compare two assault reports (defaults to latest VerisimDB runs)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "manifest" -d 'Export the AI manifest as Nickel'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "a2ml-export" -d 'Export a report file into the A2ML report-bundle document type'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "a2ml-import" -d 'Import an A2ML report-bundle file back into JSON'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "panll" -d 'Export an assault report as a PanLL event-chain model'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "help" -d 'Print detailed help text (man-style)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "assemblyline" -d 'Assemblyline: batch-scan a directory of repos (assail each, aggregate results)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "diagnostics" -d 'Run panic-attack self-diagnostics for Hypatia/gitbot-fleet visibility'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "migration-snapshot" -d 'Take a ReScript migration snapshot (assail + migration metrics)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "migration-diff" -d 'Compare two migration snapshots and produce a diff report'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "notify" -d 'Notify: generate annotated findings summary from an assemblyline report'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "image" -d 'Image: generate a system health image from an assemblyline scan (fNIRS-style)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "temporal" -d 'Temporal: navigate system health through time (diff, list, replay)'
complete -c panic-attack -n "__fish_panic_attack_needs_command" -f -a "completions" -d 'Generate shell completions for the specified shell'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -s o -l output -d 'Output report to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l signing-key -d 'Path to Ed25519 private key (32-byte seed) for signing the attestation. Requires the `signing` feature' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l logtalk -d 'Export kanren logic facts as Logtalk predicates for hypatia integration' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -s v -l verbose -d 'Verbose output'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l attest -d 'Enable attestation chain (writes .attestation.json sidecar)'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assail" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l profile -d 'Attack profile file (json/yaml)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l arg -d 'Extra argument(s) passed to the target program' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l axis-arg -d 'Axis-specific argument, format: AXIS=ARG' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l probe -d 'Probe mode for detecting unsupported flags' -r -f -a "auto\t''
always\t''
never\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -s a -l axis -d 'Attack axis to use' -r -f -a "cpu\t''
memory\t''
disk\t''
network\t''
concurrency\t''
time\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -s i -l intensity -d 'Attack intensity' -r -f -a "light\t''
medium\t''
heavy\t''
extreme\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -s d -l duration -d 'Attack duration in seconds' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand attack" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l source -d 'Source directory or file for assail analysis (defaults to PROGRAM)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l profile -d 'Attack profile file (json/yaml)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l arg -d 'Extra argument(s) passed to the target program' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l axis-arg -d 'Axis-specific argument, format: AXIS=ARG' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l probe -d 'Probe mode for detecting unsupported flags' -r -f -a "auto\t''
always\t''
never\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -s a -l axes -d 'Attack axes (default: all)' -r -f -a "cpu\t''
memory\t''
disk\t''
network\t''
concurrency\t''
time\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -s i -l intensity -d 'Attack intensity' -r -f -a "light\t''
medium\t''
heavy\t''
extreme\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -s d -l duration -d 'Attack duration per axis in seconds' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -s o -l output -d 'Output report to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assault" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l source -d 'Source directory or file for assail analysis (defaults to PROGRAM)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l timeline -d 'Timeline file (JSON/YAML) for DAW-style scheduling' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l profile -d 'Attack profile file (json/yaml) for target args' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l arg -d 'Extra argument(s) passed to the target program' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l axis-arg -d 'Axis-specific argument, format: AXIS=ARG' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -s a -l axes -d 'Stress axes to apply (default: all)' -r -f -a "cpu\t''
memory\t''
disk\t''
network\t''
concurrency\t''
time\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -s i -l intensity -d 'Stress intensity' -r -f -a "light\t''
medium\t''
heavy\t''
extreme\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -s d -l duration -d 'Ambush duration per axis in seconds' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -s o -l output -d 'Output report to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand ambush" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l preset -d 'Mutation preset when no --spec is provided' -r -f -a "light\t''
dangerous\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l spec -d 'Custom mutation combinations file (json/yaml)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l max-combinations -d 'Maximum combinations to execute' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l output-dir -d 'Directory where mutated variants are written' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l exec-program -d 'Optional executable run per mutated file' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l exec-arg -d 'Arguments for --exec-program; use {file} for the mutated file path' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -s o -l output -d 'Optional report output path (JSON)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand amuck" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l source-root -d 'Optional source root used to resolve dependency graph paths' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l scope -d 'Dependency scope for selecting related files' -r -f -a "none\t''
direct\t''
two-hops\t''
directory\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l output-dir -d 'Workspace root where abduct runs are created' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l mtime-offset-days -d 'Shift copied file mtimes by this many days (negative or positive)' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l time-mode -d 'Time mode metadata exported to executed process' -r -f -a "normal\t''
frozen\t''
slow\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l time-scale -d 'Virtual time scale factor when --time-mode slow' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l virtual-now -d 'Optional virtual timestamp (RFC3339) exported as ABDUCT_VIRTUAL_NOW' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l exec-program -d 'Optional executable to run after lock/time setup' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l exec-arg -d 'Arguments for --exec-program; placeholders: {file}, {workspace}' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l exec-timeout -d 'Timeout (seconds) for the optional execution command' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -s o -l output -d 'Optional report output path (JSON)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l no-lock -d 'Disable readonly lock-down of copied files'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand abduct" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -s o -l output -d 'Optional report output path (JSON)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand adjudicate" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l exec-program -d 'Optional executable to run for reaction observation' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l exec-arg -d 'Arguments for --exec-program; placeholder: {target}' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l repeat -d 'Number of repeated observation runs for --exec-program' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l timeout -d 'Timeout (seconds) per observation run' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l report -d 'Existing reports to observe (can be provided multiple times)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l head -d 'Include the first N lines from observed output/content' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l tail -d 'Include the last N lines from observed output/content' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l grep -d 'Exact pattern search (repeatable)' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l agrep -d 'Approximate/fuzzy pattern search (repeatable)' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l agrep-distance -d 'Maximum edit distance for --agrep matches' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l lang -d 'Output language (ISO 639-1 code: en, es, fr, de, ja)' -r -f -a "en\t''
es\t''
fr\t''
de\t''
ja\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l aspell-lang -d 'Aspell dictionary language (default derived from --lang)' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l markdown-output -d 'Optional markdown output path' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l pandoc-to -d 'Optional pandoc target format (e.g. html, docx, gfm, latex)' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l pandoc-output -d 'Optional pandoc output path (required for custom destination)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -s o -l output -d 'Optional report output path (JSON)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l aspell -d 'Enable aspell checks on observed text'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand axial" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand analyze" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand report" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand tui" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand gui" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l verisimdb-dir -d 'VerisimDB directory to scan for latest reports' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diff" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -s p -l path -d 'Alternate AI manifest file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -s o -l output -d 'Save Nickel output to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand manifest" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l kind -d 'Report kind to encode in the bundle' -r -f -a "assail\t''
attack\t''
assault\t''
ambush\t''
amuck\t''
abduct\t''
adjudicate\t''
axial\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -s o -l output -d 'Destination A2ML file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-export" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -s o -l output -d 'Destination JSON file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l kind -d 'Optional expected kind check' -r -f -a "assail\t''
attack\t''
assault\t''
ambush\t''
amuck\t''
abduct\t''
adjudicate\t''
axial\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand a2ml-import" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -s o -l output -d 'Output file for PanLL export (JSON)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand panll" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand help" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -s o -l output -d 'Output report to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l min-findings -d 'Minimum number of findings to include a repo' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l cache -d 'Path to fingerprint cache file (default: .panic-attack-cache.json in DIRECTORY)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l findings-only -d 'Only show repos with findings'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l incremental -d 'Enable incremental scanning (skip repos unchanged since last run)'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand assemblyline" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l manifest -d 'Alternate AI manifest file (default: AI.a2ml)' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand diagnostics" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l label -d 'Label for this snapshot (e.g. "before", "after", "v12-trial")' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -s o -l output -d 'Output snapshot to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l build-time -d 'Measure build time (runs `rescript build`)'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l bundle-size -d 'Measure bundle size (scans output directory)'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l store -d 'Store snapshot as VeriSimDB hexad'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-snapshot" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -s o -l output -d 'Output diff report to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l format -d 'Output format (markdown or json)' -r -f -a "markdown\t''
json\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand migration-diff" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -s o -l output -d 'Output markdown file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l min-findings -d 'Minimum findings to include a repo' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l github-owner -d 'GitHub owner for issue creation' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l critical-only -d 'Only include repos with critical findings'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l create-issues -d 'Create GitHub issues for repos with critical findings (requires gh CLI)'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand notify" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -s o -l output -d 'Output file for the system image JSON' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l cache -d 'Fingerprint cache file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l label -d 'Label for the temporal snapshot' -r
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l verisimdb-dir -d 'VeriSimDB directory for snapshots' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l incremental -d 'Enable incremental scanning'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l snapshot -d 'Take a temporal snapshot (writes to VeriSimDB)'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l panll -d 'Export PanLL-format system image alongside raw output'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand image" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -f -a "list" -d 'List all temporal snapshots'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and not __fish_seen_subcommand_from list diff" -f -a "diff" -d 'Diff two temporal snapshots'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l verisimdb-dir -d 'VeriSimDB directory' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l verisimdb-dir -d 'VeriSimDB directory' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -s o -l output -d 'Output diff report to file' -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l panll -d 'Export PanLL-format temporal diff alongside raw output'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand temporal; and __fish_seen_subcommand_from diff" -s h -l help -d 'Print help'
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l report-view -r -f -a "summary\t''
accordion\t''
dashboard\t''
matrix\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l output-format -r -f -a "json\t''
yaml\t''
nickel\t''
sarif\t''"
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l store -r -F
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l expand-sections
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l pivot
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l quiet
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -l parallel
complete -c panic-attack -n "__fish_panic_attack_using_subcommand completions" -s h -l help -d 'Print help'
