# SPDX-License-Identifier: PMPL-1.0-or-later
# panic-attack shell completions for bash
# Generated by: panic-attack completions bash
# Author: Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>

_panic-attack() {
    local i cur prev opts cmd
    COMPREPLY=()
    if [[ "${BASH_VERSINFO[0]}" -ge 4 ]]; then
        cur="$2"
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
    fi
    prev="$3"
    cmd=""
    opts=""

    for i in "${COMP_WORDS[@]:0:COMP_CWORD}"
    do
        case "${cmd},${i}" in
            ",$1")
                cmd="panic__attack"
                ;;
            panic__attack,a2ml-export)
                cmd="panic__attack__a2ml__export"
                ;;
            panic__attack,a2ml-import)
                cmd="panic__attack__a2ml__import"
                ;;
            panic__attack,abduct)
                cmd="panic__attack__abduct"
                ;;
            panic__attack,adjudicate)
                cmd="panic__attack__adjudicate"
                ;;
            panic__attack,ambush)
                cmd="panic__attack__ambush"
                ;;
            panic__attack,amuck)
                cmd="panic__attack__amuck"
                ;;
            panic__attack,analyze)
                cmd="panic__attack__analyze"
                ;;
            panic__attack,assail)
                cmd="panic__attack__assail"
                ;;
            panic__attack,assault)
                cmd="panic__attack__assault"
                ;;
            panic__attack,assemblyline)
                cmd="panic__attack__assemblyline"
                ;;
            panic__attack,attack)
                cmd="panic__attack__attack"
                ;;
            panic__attack,axial)
                cmd="panic__attack__axial"
                ;;
            panic__attack,completions)
                cmd="panic__attack__completions"
                ;;
            panic__attack,diagnostics)
                cmd="panic__attack__diagnostics"
                ;;
            panic__attack,diff)
                cmd="panic__attack__diff"
                ;;
            panic__attack,gui)
                cmd="panic__attack__gui"
                ;;
            panic__attack,help)
                cmd="panic__attack__help"
                ;;
            panic__attack,image)
                cmd="panic__attack__image"
                ;;
            panic__attack,manifest)
                cmd="panic__attack__manifest"
                ;;
            panic__attack,migration-diff)
                cmd="panic__attack__migration__diff"
                ;;
            panic__attack,migration-snapshot)
                cmd="panic__attack__migration__snapshot"
                ;;
            panic__attack,notify)
                cmd="panic__attack__notify"
                ;;
            panic__attack,panll)
                cmd="panic__attack__panll"
                ;;
            panic__attack,report)
                cmd="panic__attack__report"
                ;;
            panic__attack,temporal)
                cmd="panic__attack__temporal"
                ;;
            panic__attack,tui)
                cmd="panic__attack__tui"
                ;;
            panic__attack__temporal,diff)
                cmd="panic__attack__temporal__diff"
                ;;
            panic__attack__temporal,list)
                cmd="panic__attack__temporal__list"
                ;;
            *)
                ;;
        esac
    done

    case "${cmd}" in
        panic__attack)
            opts="-h -V --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help --version assail attack assault ambush amuck abduct adjudicate axial analyze report tui gui diff manifest a2ml-export a2ml-import panll help assemblyline diagnostics migration-snapshot migration-diff notify image temporal completions"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 1 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__a2ml__export)
            opts="-o -h --kind --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <INPUT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --kind)
                    COMPREPLY=($(compgen -W "assail attack assault ambush amuck abduct adjudicate axial" -- "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__a2ml__import)
            opts="-o -h --output --kind --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <INPUT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --kind)
                    COMPREPLY=($(compgen -W "assail attack assault ambush amuck abduct adjudicate axial" -- "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__abduct)
            opts="-o -h --source-root --scope --output-dir --no-lock --mtime-offset-days --time-mode --time-scale --virtual-now --exec-program --exec-arg --exec-timeout --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <TARGET>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --source-root)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --scope)
                    COMPREPLY=($(compgen -W "none direct two-hops directory" -- "${cur}"))
                    return 0
                    ;;
                --output-dir)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --mtime-offset-days)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --time-mode)
                    COMPREPLY=($(compgen -W "normal frozen slow" -- "${cur}"))
                    return 0
                    ;;
                --time-scale)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --virtual-now)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --exec-program)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --exec-arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --exec-timeout)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__adjudicate)
            opts="-o -h --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORTS>..."
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__ambush)
            opts="-a -i -d -o -h --source --timeline --profile --arg --axis-arg --axes --intensity --duration --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <PROGRAM>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --source)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --timeline)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --profile)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --axis-arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --axes)
                    COMPREPLY=($(compgen -W "cpu memory disk network concurrency time" -- "${cur}"))
                    return 0
                    ;;
                -a)
                    COMPREPLY=($(compgen -W "cpu memory disk network concurrency time" -- "${cur}"))
                    return 0
                    ;;
                --intensity)
                    COMPREPLY=($(compgen -W "light medium heavy extreme" -- "${cur}"))
                    return 0
                    ;;
                -i)
                    COMPREPLY=($(compgen -W "light medium heavy extreme" -- "${cur}"))
                    return 0
                    ;;
                --duration)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -d)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__amuck)
            opts="-o -h --preset --spec --max-combinations --output-dir --exec-program --exec-arg --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <TARGET>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --preset)
                    COMPREPLY=($(compgen -W "light dangerous" -- "${cur}"))
                    return 0
                    ;;
                --spec)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --max-combinations)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output-dir)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --exec-program)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --exec-arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__analyze)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__assail)
            opts="-o -v -h --output --verbose --attest --signing-key --logtalk --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <TARGET>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --signing-key)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --logtalk)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__assault)
            opts="-a -i -d -o -h --source --profile --arg --axis-arg --probe --axes --intensity --duration --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <PROGRAM>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --source)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --profile)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --axis-arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --probe)
                    COMPREPLY=($(compgen -W "auto always never" -- "${cur}"))
                    return 0
                    ;;
                --axes)
                    COMPREPLY=($(compgen -W "cpu memory disk network concurrency time" -- "${cur}"))
                    return 0
                    ;;
                -a)
                    COMPREPLY=($(compgen -W "cpu memory disk network concurrency time" -- "${cur}"))
                    return 0
                    ;;
                --intensity)
                    COMPREPLY=($(compgen -W "light medium heavy extreme" -- "${cur}"))
                    return 0
                    ;;
                -i)
                    COMPREPLY=($(compgen -W "light medium heavy extreme" -- "${cur}"))
                    return 0
                    ;;
                --duration)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -d)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__assemblyline)
            opts="-o -h --output --findings-only --min-findings --incremental --cache --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <DIRECTORY>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --min-findings)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --cache)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__attack)
            opts="-a -i -d -h --profile --arg --axis-arg --probe --axis --intensity --duration --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <PROGRAM>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --profile)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --axis-arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --probe)
                    COMPREPLY=($(compgen -W "auto always never" -- "${cur}"))
                    return 0
                    ;;
                --axis)
                    COMPREPLY=($(compgen -W "cpu memory disk network concurrency time" -- "${cur}"))
                    return 0
                    ;;
                -a)
                    COMPREPLY=($(compgen -W "cpu memory disk network concurrency time" -- "${cur}"))
                    return 0
                    ;;
                --intensity)
                    COMPREPLY=($(compgen -W "light medium heavy extreme" -- "${cur}"))
                    return 0
                    ;;
                -i)
                    COMPREPLY=($(compgen -W "light medium heavy extreme" -- "${cur}"))
                    return 0
                    ;;
                --duration)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -d)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__axial)
            opts="-o -h --exec-program --exec-arg --repeat --timeout --report --head --tail --grep --agrep --agrep-distance --lang --aspell --aspell-lang --markdown-output --pandoc-to --pandoc-output --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <TARGET>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --exec-program)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --exec-arg)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --repeat)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --timeout)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --head)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --tail)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --grep)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --agrep)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --agrep-distance)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --lang)
                    COMPREPLY=($(compgen -W "en es fr de ja" -- "${cur}"))
                    return 0
                    ;;
                --aspell-lang)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --markdown-output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --pandoc-to)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --pandoc-output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__completions)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help bash zsh fish nushell powershell"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__diagnostics)
            opts="-h --manifest --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --manifest)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__diff)
            opts="-h --verisimdb-dir --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help [BASE] [COMPARE]"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --verisimdb-dir)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__gui)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__help)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help [COMMAND]"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__image)
            opts="-o -h --output --incremental --cache --snapshot --label --verisimdb-dir --panll --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <DIRECTORY>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --cache)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --label)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --verisimdb-dir)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__manifest)
            opts="-p -o -h --path --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --path)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -p)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__migration__diff)
            opts="-o -h --output --format --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <BEFORE> <AFTER>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --format)
                    COMPREPLY=($(compgen -W "markdown json" -- "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__migration__snapshot)
            opts="-o -h --label --build-time --bundle-size --store --output --report-view --expand-sections --output-format --pivot --quiet --parallel --help <TARGET>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --label)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__notify)
            opts="-o -h --output --critical-only --min-findings --create-issues --github-owner --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --min-findings)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --github-owner)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__panll)
            opts="-o -h --output --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__report)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__temporal)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help list diff"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__temporal__diff)
            opts="-o -h --verisimdb-dir --output --panll --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <FROM> <TO>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --verisimdb-dir)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --output)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                -o)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__temporal__list)
            opts="-h --verisimdb-dir --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --verisimdb-dir)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
        panic__attack__tui)
            opts="-h --report-view --expand-sections --output-format --pivot --store --quiet --parallel --help <REPORT>"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            case "${prev}" in
                --report-view)
                    COMPREPLY=($(compgen -W "summary accordion dashboard matrix" -- "${cur}"))
                    return 0
                    ;;
                --output-format)
                    COMPREPLY=($(compgen -W "json yaml nickel sarif" -- "${cur}"))
                    return 0
                    ;;
                --store)
                    COMPREPLY=($(compgen -f "${cur}"))
                    return 0
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            return 0
            ;;
    esac
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    complete -F _panic-attack -o nosort -o bashdefault -o default panic-attack
else
    complete -F _panic-attack -o bashdefault -o default panic-attack
fi
