// SPDX-License-Identifier: PMPL-1.0-or-later

//! miniKanren-inspired relational logic engine for panic-attack
//!
//! Provides:
//! - **Relational fact database** with unification-based queries
//! - **Taint analysis** tracking data flow from sources to sinks
//! - **Cross-language reasoning** for multi-language codebases
//! - **Search strategies** for prioritising analysis order
//!
//! Inspired by miniKanren (Byrd, Friedman) and Mozart/Oz constraint
//! programming, adapted for static analysis of source code.

pub mod core;
pub mod crosslang;
pub mod strategy;
pub mod taint;

#[allow(unused_imports)]
pub use self::core::{FactDB, LogicEngine};
#[allow(unused_imports)]
pub use crosslang::CrossLangAnalyzer;
#[allow(unused_imports)]
pub use strategy::SearchStrategy;
#[allow(unused_imports)]
pub use taint::{TaintAnalyzer, TaintSink, TaintSource};

/// Export all facts in the FactDB as Logtalk predicates.
///
/// Generates a Logtalk source file that can be loaded by hypatia's
/// neurosymbolic reasoning engine for cross-project learning.
///
/// Exported relations:
/// - `taint_source/2`, `taint_sink/2`, `data_flow/2`
/// - `tainted_path/4`, `critical_vuln/2`, `high_vuln/2`
/// - `cross_lang_call/3`, `cross_lang_vuln/3`
/// - `weak_point/3`, `file_risk/2`, `language/1`, `framework/1`
/// - `suppressed/2` (FP suppression results)
pub fn export_logtalk(db: &FactDB) -> String {
    use self::core::Term;

    let mut output = String::new();
    output.push_str("%% SPDX-License-Identifier: PMPL-1.0-or-later\n");
    output.push_str("%% Auto-generated by panic-attack kanren engine\n");
    output.push_str("%% For import into hypatia neurosymbolic reasoning layer\n\n");
    output.push_str(":- object(panic_attack_facts).\n\n");

    let relations = [
        "taint_source", "taint_sink", "data_flow", "tainted_path",
        "critical_vuln", "high_vuln", "cross_lang_call", "cross_lang_vuln",
        "weak_point", "file_risk", "language", "framework",
        "suppressed", "context",
    ];

    for relation in &relations {
        let facts = db.get_facts(relation);
        if facts.is_empty() {
            continue;
        }
        output.push_str(&format!("  %% {}/{}\n", relation, facts[0].args.len()));
        for fact in &facts {
            output.push_str("  ");
            output.push_str(relation);
            output.push('(');
            for (i, arg) in fact.args.iter().enumerate() {
                if i > 0 {
                    output.push_str(", ");
                }
                match arg {
                    Term::Atom(s) => {
                        // Escape single quotes in Logtalk atoms
                        let escaped = s.replace('\'', "\\'");
                        output.push('\'');
                        output.push_str(&escaped);
                        output.push('\'');
                    }
                    Term::Int(n) => {
                        output.push_str(&n.to_string());
                    }
                    other => {
                        output.push_str(&format!("'{:?}'", other));
                    }
                }
            }
            output.push_str(").\n");
        }
        output.push('\n');
    }

    output.push_str(":- end_object.\n");
    output
}

/// Write Logtalk export to a file.
pub fn write_logtalk_export(
    db: &FactDB,
    output: &std::path::Path,
) -> anyhow::Result<()> {
    let content = export_logtalk(db);
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output, content)?;
    Ok(())
}
